cmake_minimum_required(VERSION 3.18)
project(UltraNAM LANGUAGES CXX C)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_OSX_DEPLOYMENT_TARGET 13.0)
set(NAM_ROOT ${CMAKE_CURRENT_SOURCE_DIR}/../Vendor/NeuralAmpModelerCore)
file(GLOB NAM_SOURCES ${NAM_ROOT}/NAM/*.cpp ${NAM_ROOT}/NAM/*.c ${NAM_ROOT}/NAM/*/*.cpp)
add_executable(nam-ir nam-ir.cpp ${NAM_SOURCES})
target_include_directories(nam-ir PRIVATE ${NAM_ROOT} ${NAM_ROOT}/Dependencies/eigen ${NAM_ROOT}/Dependencies/nlohmann)
target_compile_options(nam-ir PRIVATE -O2 -w)
if(APPLE)
  target_include_directories(nam-ir SYSTEM PRIVATE "${CMAKE_OSX_SYSROOT}/usr/include/c++/v1")
endif()
